default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: url_shortener_service_development
  host: localhost
  username: postgres
  password: password

test:
  <<: *default
  database: url_shortener_service_test
  host: localhost
  username: postgres
  password: password

production:
  <<: *default
  database: url_shortener_service_production
  username: url_shortener_service
  password: <%= ENV["URL_SHORTENER_SERVICE_DATABASE_PASSWORD"] %>
